#!/usr/bin/env bash
# Install nginx on web server

sudo apt-get -y update
sudo apt-get install nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
