#!/usr/bin/env bash
# Install nginx on web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 deault_server/a rewrite ^redirect)me https://bogadeji.netlify.app permanent:'
/etc/nginx/sites-enabled/default
sudo service nginx start
