#!/usr/bin/env bash
# Install nginx on web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '24i\	 rewrite ^/redirect_me https://bogadeji.netlify.app permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	 error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx start
