#!/usr/bin/env bash
# install load balancer


echo -e "Run script...\n"
#install haproxy #install haproxy

sudo apt-get -y update
sudo apt-get install -y haproxy
echo "ENABLED=1" > /etc/default/haproxy

sudo echo "
frontend Abby
        bind *:80
        mode http
        default_backend app

backend app
        balance roundrobin
        server 33948-web-01 54.175.32.111:80 check
    server 33948-web-02 34.207.63.99:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart

echo -e "web-01 web-02"
echo "web-01"
echo "web-02"
