#!/usr/bin/env bash
# This script display numbers 1 to 100
# Display FizzBuzz when the number is a multiple of 3 and 5
# Display Fizz when the number is a multiple of 3
# Display Buzz when the number is a multiple of 5
# Otherwise, display the number

count=1
while [ $count -le 100 ]
do
	if (( count % 3 == 0 && count % 5 == 0))
	then
		echo "FizzBuzz"
	elif (( count % 3 == 0 ))
	then
		echo "Fizz"
	elif (( count % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$count"
	fi
	(( count++ ))
done
