#!/usr/bin/env bash
# run apache on docker container

sudo apt-get updtae -y
sudo apt-et install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
